image: Visual Studio 2017
clone_folder: C:\TBuild\tdesktop
test: off
deploy: off

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  matrix:
   - BUILD_VERSION:
   - BUILD_VERSION: disable_register_custom_scheme
   - BUILD_VERSION: disable_crash_reports
   - BUILD_VERSION: disable_network_proxy

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegram.sln

after_build:

- ps: | # package artifacts
      7z a -m0=LZMA2 -mx9 full.7z C:\TBuild
      


artifacts:
  - path: out\Debug\Telegram.exe
    name: Telegram_debug.exe
  - path: out\Debug\Telegram.exe.pdb
    name: Telegram_debug.exe.pdb
  - path: full.7z
    name: full
